COMPONENT = ../maze/SourceBroadcasterAppC

CFLAGS += -I"../maze"
CFLAGS += $(SLP_PARAMETER_CFLAGS)

include ../common/tinyos/makefile.common

#include $(TINYOS_ROOT_DIR)/Makefile.include
include $(MAKERULES)
